server:
  port: 8086
spring:
  application:
    name: spring-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Cttdoje/spring-cloud-config-repo
          username:
          password: