server:
  port: 8081
spring:
  application:
    name: server-user
  cloud:
    config:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka3000.com:3000/eureka/,http://eureka3001.com:3001/eureka/,http://eureka3002.com:3002/eureka/  #会往其中随机注册一台,注册一台成功即可
  instance:
    instance-id: user #此实例注册到eureka服务端的唯一的实例ID
    prefer-ip-address: true  #是否显示IP
    lease-renewal-interval-in-seconds: 10 #eureka客户需要多长时间发送心跳给eureka服务器，表明它仍 然活着,默认为30 秒 (与下面配置的单位都是秒)
    lease-expiration-duration-in-seconds: 30 #Eureka服务器在接收到实例的最后一次发出的心跳后，需要 等待多久才可以将此实例删除，默认为90秒

#feign 开启支持 hystrix
feign:
  hystrix:
    enabled: true

#hystrix 断路器配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000  #设置超时时间为多少，然后进行服务降级
      circuitBreaker:
        requestVolumeThreshold: 5  #请求失败次数，达到后将进行熔断


management:
  endpoints:
    web:
      exposure:
        include: beans,health,info,conditions,heapdump,shutdown,mappings,threaddump
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true