server:
  port: 3000

eureka:
  server:
    enable-self-preservation: false   #关闭自我保护机制
    eviction-interval-timer-in-ms: 4000  #设置清理间隔(单位:毫秒 默认是60*1000)
  instance:
    hostname: eureka3000.com
  client:
    registerWithEureka: false # 单点的时候设置为 false 禁止注册自身
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:3000/eureka
spring:
  application:
    name: eureka
#添加权限
#  security:
#    basic:
#      enabled: true
#    user:
#      name: user
#      password: 123qwe
