server:
  port: 3001


eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
  instance:
    hostname: eureka3001.com
  client:
    #register-with-eureka: false
    #fetch-registry: false
    service-url:
      defaultZone: http://eureka3000.com:3000/eureka/,http://eureka3002.com:3002/eureka/
spring:
  application:
    name: eureka
#  security:
#    basic:
#      enabled: true
#    user:
#      name: user
#      password: 123qwe
